version: '3.8'

services:
  db:
    container_name: nodejs2022Q2-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

  nest:
    container_name: nodejs2022Q2-nest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db

networks:
  db:
    name: 'nodejs2022Q2-network'
    driver: bridge
